### ISSUE TITLE
Feature idea: permalinks

### ISSUE THREAD

**Issue by kubukoz** [daddykotex/smithy4s-code-generation#14]
Some playgrounds with code snippets support this, e.g.

https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgzhATlAvFA3gKCjqA7AQwFsIAuKOYRASzwHNtcC6z8BXIgIyUZ2oBNylGvUwBfTEA

I'm not sure what encoding it is, but the original was

```typescript
type User = {
    name: string
    age: number
    id: string
}
```

.

We could start by base64-encoding the input, or find a more optimal encoding for code such as the one used by typescript playground.

The "identifier" of the snippet would automatically update the URI in the browser for easy copy-pasting.

**Comment by kubukoz** [comment]
ok, I got it - `lzstring.compressToEncodedURIComponent` from https://pieroxy.net/blog/pages/lz-string/index.html . There are [typings](https://www.npmjs.com/package/@types/lz-string) so we could use ScalablyTyped for the bindings, but given it's just ~2 methods we could write the JS stubs manually too.

**Comment by daddykotex** [comment]
That's a must have, I thought about it a while back but forgot to record an issue for it, thanks for that

**Comment by kubukoz** [comment]
I'll give it a go.
